import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableCell,
  TableRow,
  WidthType,
  AlignmentType,
  BorderStyle,
  Header,
  Footer,
  HeadingLevel,
  ShadingType,
} from "docx";
import type { StudentProfile, DailyAttendanceLog, StudentAttendanceSummary } from "./student-attendance-data";

/**
 * Downloads a Blob as a Word file (.docx) in the user's browser
 */
async function downloadDocxBlob(doc: Document, filename: string) {
  const blob = await Packer.toBlob(doc);
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}

// Styling Constants for clean, professional Word document layout
const COLOR_PRIMARY = "6B21A8"; // Deep Purple
const COLOR_ACCENT = "0284C7"; // Sky Blue
const COLOR_BG_HEADER = "F3E8FF"; // Soft Purple Tint
const COLOR_BG_ZEBRA = "F8FAFC"; // Light Gray Tint
const COLOR_BORDER = "E2E8F0"; // Border Gray

type Alignment = typeof AlignmentType[keyof typeof AlignmentType];

/**
 * Generates and downloads an Individual Student Word Document Report (.docx)
 */
export async function exportIndividualStudentReport(
  student: StudentProfile,
  logs: DailyAttendanceLog[],
  summary: StudentAttendanceSummary,
  startDateStr: string,
  endDateStr: string
) {
  const studentLogs = logs.filter((l) => l.studentId === student.id);

  const doc = new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "Lumo Buddy Learning Platform — Student Attendance & Time Slot Report",
                    size: 18,
                    color: "64748B",
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Confidential Student Progress Report • Generated by Lumo Buddy System",
                    size: 16,
                    color: "94A3B8",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Title
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({
                text: `Student Attendance & Daily Session Report`,
                bold: true,
                size: 36,
                color: COLOR_PRIMARY,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Individual Progress & Daily 12 PM - 5 PM Time Slot Logs for `,
                size: 22,
                color: "475569",
              }),
              new TextRun({
                text: student.name,
                bold: true,
                size: 22,
                color: COLOR_PRIMARY,
              }),
            ],
          }),

          new Paragraph({ text: "" }), // spacing

          // Student Info Card Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createStyledTableCell("Student Name", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell(student.name, false, "FFFFFF", 70),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell("Age & Gender", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell(`${student.age} Years (${student.gender})`, false, "FFFFFF", 70),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell("Support Level", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell(student.supportLevelLabel, false, "FFFFFF", 70),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell("Primary Learning Target", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell(student.primaryGoal, false, "FFFFFF", 70),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell("Report Date Range", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell(`${startDateStr} to ${endDateStr}`, false, "FFFFFF", 70),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell("Designated Time Window", true, COLOR_BG_HEADER, 30),
                  createStyledTableCell("12:00 NOON to 5:00 PM (1-Hour Daily Window)", false, "FFFFFF", 70),
                ],
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Attendance Summary Overview Header
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "1. Attendance & Play Time Overview",
                bold: true,
                size: 26,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Summary Stats Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createStyledTableCell("Total Days Evaluated", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Attendance Rate", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Total Time Played", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Average Accuracy", true, COLOR_BG_HEADER, 25),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell(`${summary.totalDays} Days`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell(`${summary.attendanceRate}%`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell(`${summary.totalPlayedHours} Hours`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell(`${summary.avgAccuracy}%`, false, "FFFFFF", 25, AlignmentType.CENTER),
                ],
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Day-by-Day Log Table Header
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "2. Day-by-Day Attendance & Time Slot Logs (12 PM - 5 PM Window)",
                bold: true,
                size: 26,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: "The table below records daily attendance, start time, end time, session counts, total played duration, and accuracy for each date.",
                italics: true,
                size: 18,
                color: "64748B",
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Daily Logs Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              // Header Row
              new TableRow({
                children: [
                  createStyledTableCell("Date", true, COLOR_BG_HEADER, 15),
                  createStyledTableCell("Status", true, COLOR_BG_HEADER, 12),
                  createStyledTableCell("Start Time", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("End Time", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("Duration", true, COLOR_BG_HEADER, 13),
                  createStyledTableCell("Sessions", true, COLOR_BG_HEADER, 10),
                  createStyledTableCell("Accuracy", true, COLOR_BG_HEADER, 11),
                  createStyledTableCell("Games Played", true, COLOR_BG_HEADER, 11),
                ],
              }),

              // Log Rows
              ...studentLogs.map((log, idx) => {
                const bg = idx % 2 === 0 ? "FFFFFF" : COLOR_BG_ZEBRA;
                return new TableRow({
                  children: [
                    createStyledTableCell(`${log.date} (${log.dayOfWeek})`, false, bg, 15),
                    createStyledTableCell(log.status, false, bg, 12),
                    createStyledTableCell(log.startTime, false, bg, 14),
                    createStyledTableCell(log.endTime, false, bg, 14),
                    createStyledTableCell(log.status === "Missed" ? "-" : `${log.playedMinutes} mins`, false, bg, 13),
                    createStyledTableCell(log.status === "Missed" ? "0" : `${log.sessionsCount}`, false, bg, 10),
                    createStyledTableCell(log.status === "Missed" ? "-" : `${log.accuracy}%`, false, bg, 11),
                    createStyledTableCell(log.gamesPlayed.length > 0 ? log.gamesPlayed.join(", ") : "-", false, bg, 11),
                  ],
                });
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Recommendations & Support Notes Section
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "3. Pedagogical Observations & Recommendations",
                bold: true,
                size: 26,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `• Time Slot Consistency: `,
                bold: true,
                size: 20,
              }),
              new TextRun({
                text: `${student.name} maintains a steady learning rhythm during the preferred afternoon window (${summary.preferredTimeSlot}).`,
                size: 20,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `• Total Duration Accuracy: `,
                bold: true,
                size: 20,
              }),
              new TextRun({
                text: `Daily total played time averages ${summary.avgDailyMinutes} minutes per session day, keeping cumulative playtime accurately preserved without overloading the child.`,
                size: 20,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `• Recommended Action: `,
                bold: true,
                size: 20,
              }),
              new TextRun({
                text: `Continue offering games aligned with ${student.primaryGoal} during the 12 NOON - 5 PM window for optimal engagement and calm learning.`,
                size: 20,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const filename = `${student.name.replace(/\s+/g, "_")}_Attendance_Report_${startDateStr}_to_${endDateStr}.docx`;
  await downloadDocxBlob(doc, filename);
}

/**
 * Generates and downloads a Master All-10-Students Attendance Word Document Report (.docx)
 */
export async function exportAllStudentsAttendanceReport(
  students: StudentProfile[],
  allLogs: DailyAttendanceLog[],
  startDateStr: string,
  endDateStr: string
) {
  // Compute summary stats for each student
  const studentSummaries = students.map((s) => {
    const sLogs = allLogs.filter((l) => l.studentId === s.id);
    const totalDays = sLogs.length;
    const daysPresent = sLogs.filter((l) => l.status === "Present").length;
    const daysPartial = sLogs.filter((l) => l.status === "Partial").length;
    const totalMinutes = sLogs.reduce((sum, l) => sum + l.playedMinutes, 0);
    const activeLogs = sLogs.filter((l) => l.status !== "Missed");
    const avgAcc = activeLogs.length > 0 ? Math.round(activeLogs.reduce((sum, l) => sum + l.accuracy, 0) / activeLogs.length) : 0;
    const attRate = totalDays > 0 ? Math.round(((daysPresent + daysPartial * 0.5) / totalDays) * 100) : 0;

    return {
      student: s,
      totalDays,
      daysPresent,
      daysPartial,
      totalMinutes,
      totalHours: (totalMinutes / 60).toFixed(1),
      avgAcc,
      attRate,
    };
  });

  const overallClassAttRate = Math.round(
    studentSummaries.reduce((sum, s) => sum + s.attRate, 0) / (students.length || 1)
  );
  const totalClassHours = (
    studentSummaries.reduce((sum, s) => sum + s.totalMinutes, 0) / 60
  ).toFixed(1);

  const doc = new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "Lumo Buddy Learning Platform — 10-Student Master Attendance & Time Slot Report",
                    size: 18,
                    color: "64748B",
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Master Student Attendance Register • Lumo Buddy Supportive Learning System",
                    size: 16,
                    color: "94A3B8",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Title
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({
                text: `Master 10-Student Attendance & Time Slot Register`,
                bold: true,
                size: 34,
                color: COLOR_PRIMARY,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Combined Day-by-Day Attendance, Start/End Times (12 PM - 5 PM Slot), and Play Duration`,
                size: 20,
                color: "475569",
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Evaluation Date Range: ${startDateStr} to ${endDateStr}`,
                bold: true,
                size: 20,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Class Overview Card
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createStyledTableCell("Total Enrolled Students", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Class Attendance Rate", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Cumulative Class Play Time", true, COLOR_BG_HEADER, 25),
                  createStyledTableCell("Daily Time Slot Window", true, COLOR_BG_HEADER, 25),
                ],
              }),
              new TableRow({
                children: [
                  createStyledTableCell(`${students.length} Students`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell(`${overallClassAttRate}%`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell(`${totalClassHours} Hours`, false, "FFFFFF", 25, AlignmentType.CENTER),
                  createStyledTableCell("12:00 PM - 05:00 PM", false, "FFFFFF", 25, AlignmentType.CENTER),
                ],
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Master 10-Student Table Header
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "1. 10-Student Summary Attendance & Performance Table",
                bold: true,
                size: 26,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Master Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createStyledTableCell("Student Name", true, COLOR_BG_HEADER, 18),
                  createStyledTableCell("Support Level", true, COLOR_BG_HEADER, 18),
                  createStyledTableCell("Days Present", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("Total Play Time", true, COLOR_BG_HEADER, 16),
                  createStyledTableCell("Avg Accuracy", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("Attendance Rate", true, COLOR_BG_HEADER, 20),
                ],
              }),

              ...studentSummaries.map((s, idx) => {
                const bg = idx % 2 === 0 ? "FFFFFF" : COLOR_BG_ZEBRA;
                return new TableRow({
                  children: [
                    createStyledTableCell(s.student.name, true, bg, 18),
                    createStyledTableCell(`Level ${s.student.supportLevel}`, false, bg, 18),
                    createStyledTableCell(`${s.daysPresent} / ${s.totalDays} Days`, false, bg, 14, AlignmentType.CENTER),
                    createStyledTableCell(`${s.totalHours} Hours`, false, bg, 16, AlignmentType.CENTER),
                    createStyledTableCell(`${s.avgAcc}%`, false, bg, 14, AlignmentType.CENTER),
                    createStyledTableCell(`${s.attRate}%`, false, bg, 20, AlignmentType.CENTER),
                  ],
                });
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Day-by-Day Master Log Section Header
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "2. Comprehensive Daily Time Slot Register (12 PM - 5 PM Window)",
                bold: true,
                size: 26,
                color: COLOR_ACCENT,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: "Complete audit log showing daily attendance status, logged start time, end time, session counts, and duration for all students.",
                italics: true,
                size: 18,
                color: "64748B",
              }),
            ],
          }),

          new Paragraph({ text: "" }),

          // Master Log Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createStyledTableCell("Date", true, COLOR_BG_HEADER, 12),
                  createStyledTableCell("Student", true, COLOR_BG_HEADER, 18),
                  createStyledTableCell("Status", true, COLOR_BG_HEADER, 12),
                  createStyledTableCell("Start Time", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("End Time", true, COLOR_BG_HEADER, 14),
                  createStyledTableCell("Duration", true, COLOR_BG_HEADER, 12),
                  createStyledTableCell("Sessions", true, COLOR_BG_HEADER, 9),
                  createStyledTableCell("Accuracy", true, COLOR_BG_HEADER, 9),
                ],
              }),

              ...allLogs.map((log, idx) => {
                const bg = idx % 2 === 0 ? "FFFFFF" : COLOR_BG_ZEBRA;
                return new TableRow({
                  children: [
                    createStyledTableCell(log.date, false, bg, 12),
                    createStyledTableCell(log.studentName, true, bg, 18),
                    createStyledTableCell(log.status, false, bg, 12),
                    createStyledTableCell(log.startTime, false, bg, 14),
                    createStyledTableCell(log.endTime, false, bg, 14),
                    createStyledTableCell(log.status === "Missed" ? "-" : `${log.playedMinutes}m`, false, bg, 12),
                    createStyledTableCell(log.status === "Missed" ? "0" : `${log.sessionsCount}`, false, bg, 9),
                    createStyledTableCell(log.status === "Missed" ? "-" : `${log.accuracy}%`, false, bg, 9),
                  ],
                });
              }),
            ],
          }),
        ],
      },
    ],
  });

  const filename = `All_10_Students_Master_Attendance_${startDateStr}_to_${endDateStr}.docx`;
  await downloadDocxBlob(doc, filename);
}

/**
 * Helper to construct styled TableCell for docx
 */
function createStyledTableCell(
  text: string,
  isBold = false,
  bgColor = "FFFFFF",
  widthPercentage = 20,
  alignment: Alignment = AlignmentType.LEFT
): TableCell {
  return new TableCell({
    width: { size: widthPercentage, type: WidthType.PERCENTAGE },
    shading: { fill: bgColor, type: ShadingType.CLEAR },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 4, color: COLOR_BORDER },
      bottom: { style: BorderStyle.SINGLE, size: 4, color: COLOR_BORDER },
      left: { style: BorderStyle.SINGLE, size: 4, color: COLOR_BORDER },
      right: { style: BorderStyle.SINGLE, size: 4, color: COLOR_BORDER },
    },
    children: [
      new Paragraph({
        alignment,
        children: [
          new TextRun({
            text,
            bold: isBold,
            size: 18,
            color: isBold ? "1E293B" : "334155",
          }),
        ],
      }),
    ],
  });
}
